version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: vivo_postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: rootpassword
      POSTGRES_DB: vivo_db
    ports:
      - "5432:5432"
    volumes:
      - vivo_pg_data:/var/lib/postgresql/data

volumes:
  vivo_pg_data: